Move jar files
Move resource files -> change the required details like passwords, server names, sid, etc..,.
Move the shell scripts
Move mail package, new package and stats tables in utility

--CCN_UTILITY
DROP TABLE CCN_BATCH_JOBS_INTRFC_DTLS;
DROP TABLE CCN_BATCH_JOBS_STATS;

CREATE TABLE CCN_BATCH_JOBS_STATS (
    CCN_BATCH_JOBS_STATS_ID    INTEGER,
    BATCH_NAME                 VARCHAR2(200) NOT NULL,
    START_TIMESTAMP            DATE NOT NULL,
    END_TIMESTAMP              DATE,
    BATCH_STATUS               VARCHAR2(100) NOT NULL,
    CONSTRAINT CCN_BATCH_JOBS_STATS_PK PRIMARY KEY (CCN_BATCH_JOBS_STATS_ID));
CREATE TABLE CCN_BATCH_JOBS_INTRFC_DTLS (
    CCN_BATCH_JOBS_INTRFC_DTLS_ID  INTEGER,
    CCN_BATCH_JOBS_STATS_ID        INTEGER NOT NULL,
    INTRFC_TYPE                    VARCHAR2(10) NOT NULL,
    LOAD_DATE                      DATE NOT NULL,
    DATAFILE_CONTENTS              CLOB NOT NULL,
    DATAFILE_NAME                  CLOB NOT NULL,
    CONSTRAINT CCN_BATCH_JOBS_INTRFC_DTLS_PK PRIMARY KEY (CCN_BATCH_JOBS_INTRFC_DTLS_ID),
    CONSTRAINT CCN_BATCH_JOBS_INTRFC_DTLS_FK FOREIGN KEY (CCN_BATCH_JOBS_STATS_ID) REFERENCES CCN_BATCH_JOBS_STATS (CCN_BATCH_JOBS_STATS_ID));

/*
SELECT *--A.*,B.*
  FROM CCN_BATCH_JOBS_STATS A,
       CCN_BATCH_JOBS_INTRFC_DTLS B
 WHERE A.CCN_BATCH_JOBS_STATS_ID = B.CCN_BATCH_JOBS_STATS_ID(+)
 ORDER BY A.BATCH_NAME, A.CCN_BATCH_JOBS_STATS_ID;
*/

CCN_BATCH_JOBS_STATS_PKG.PKS
CCN_BATCH_JOBS_STATS_PKG.PKG

--COSTCNTR
GRANT EXECUTE ON CCN_BATCH_PROCESS               to CCNUSER;
CREATE OR REPLACE SYNONYM CCNUSER.CCN_BATCH_PROCESS FOR COSTCNTR.CCN_BATCH_PROCESS;
GRANT EXECUTE ON CCN_HIERARCHY_FUT_TO_CURR_PKG   to CCNUSER;
CREATE OR REPLACE SYNONYM CCNUSER.CCN_HIERARCHY_FUT_TO_CURR_PKG FOR COSTCNTR.CCN_HIERARCHY_FUT_TO_CURR_PKG;
GRANT EXECUTE ON CCN_RESTRICTION_PKG             to CCNUSER;
CREATE OR REPLACE SYNONYM CCNUSER.CCN_RESTRICTION_PKG FOR COSTCNTR.CCN_RESTRICTION_PKG;
GRANT SELECT, INSERT ON COST_CENTER_OTHER_1 TO CCNUSER;
CREATE OR REPLACE SYNONYM CCNUSER.COST_CENTER_OTHER_1 FOR COSTCNTR.COST_CENTER_OTHER_1;

--CSTMR_DPSTS
GRANT EXECUTE ON CUSTOMER_DEPOSITS_DAILY_LOAD    to CSTMR_DPSTS_USR;
CREATE OR REPLACE SYNONYM CSTMR_DPSTS_USR.CUSTOMER_DEPOSITS_DAILY_LOAD FOR CSTMR_DPSTS.CUSTOMER_DEPOSITS_DAILY_LOAD;
GRANT EXECUTE ON CUST_DEP_BATCH_PKG              to CSTMR_DPSTS_USR;
CREATE OR REPLACE SYNONYM CSTMR_DPSTS_USR.CUST_DEP_BATCH_PKG FOR CSTMR_DPSTS.CUST_DEP_BATCH_PKG;

--STORDRFT
  --DROP TABLE PAID_DETAILS_ROYAL;
  --DROP TABLE PAID_DETAILS_ROYAL_HST;
  CREATE TABLE PAID_DETAILS_ROYAL
   (TRANSACTION_NUMBER      VARCHAR2(5), 
    ACCOUNT_NUMBER          VARCHAR2(7), 
    TRANSACTION_TYPE_CODE   VARCHAR2(2), 
    SUB_REPORT_CODE         VARCHAR2(2), 
    SERIAL_NUMBER_STORE     VARCHAR2(4), 
    SERIAL_NUMBER_SEQUENCE  VARCHAR2(4), 
    AMOUNT                  VARCHAR2(11), 
    STATUS_FLAG             VARCHAR2(2), 
    ISSUE_DATE              VARCHAR2(6), 
    PAID_DATE               VARCHAR2(6), 
    TRANSACTION_CODE        VARCHAR2(3),
    FILLER                  VARCHAR2(1),
    CHECK_NUMBER_CC         VARCHAR2(4), 
    CHECK_NUMBER_SQ         VARCHAR2(4), 
    CHECK_NUMBER_CK         VARCHAR2(1), 
    FILLER1                 VARCHAR2(9), 
    STATUS                  VARCHAR2(2), 
    TOLERANCE_AMOUNT        VARCHAR2(3), 
    TOLERANCE_INDICATOR     VARCHAR2(1)
   );
   CREATE TABLE PAID_DETAILS_ROYAL_HST AS SELECT A.*, SYSDATE AS LOAD_DATE, 10 AS RUN_NBR FROM PAID_DETAILS_ROYAL A WHERE 1=2;

  --DROP TABLE PAID_DETAILS_SUNTRUST;
  --DROP TABLE PAID_DETAILS_SUNTRUST_HST;
  CREATE TABLE PAID_DETAILS_SUNTRUST
   (FILLER                   VARCHAR2(1), 
    TRANSACTION_TYPE_CODE    VARCHAR2(2), 
    PAID_BANK_NUMBER         VARCHAR2(3), 
    PAID_ACCOUNT_NUMBER      VARCHAR2(10), 
    PAID_CHECK_SERIAL_NUMBER VARCHAR2(10), 
    PAID_DATE_PAID           VARCHAR2(6), 
    PAID_AMONUT_ITEMS        VARCHAR2(10), 
    PAID_CPCS_NUMBER         VARCHAR2(9)
   );
   CREATE TABLE PAID_DETAILS_SUNTRUST_HST AS SELECT A.*, SYSDATE AS LOAD_DATE, 10 AS RUN_NBR FROM PAID_DETAILS_SUNTRUST A WHERE 1=2;

GRANT SELECT, INSERT ON PAID_DETAILS_ROYAL     to STDRFTUSR;
CREATE OR REPLACE SYNONYM STDRFTUSR.PAID_DETAILS_ROYAL FOR STORDRFT.PAID_DETAILS_ROYAL;
GRANT SELECT, INSERT ON PAID_DETAILS_SUNTRUST  to STDRFTUSR;
CREATE OR REPLACE SYNONYM STDRFTUSR.PAID_DETAILS_SUNTRUST FOR STORDRFT.PAID_DETAILS_SUNTRUST;
GRANT EXECUTE ON SD_PAID_DETAILS_LOAD  to STDRFTUSR;
CREATE OR REPLACE SYNONYM STDRFTUSR.SD_PAID_DETAILS_LOAD FOR STORDRFT.SD_PAID_DETAILS_LOAD;